[project]
name = "miet-scheduler"
version = "0.1.0"
description = "Выгрузка учебного расписания МИЭТ (miet.ru) в календарь формата iCalendar (.ics)"
readme = "README.md"
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "ical>=14.2.0",
]

[project.scripts]
miet-scheduler = "miet_scheduler.cli:main"

[build-system]
requires = ["uv_build>=0.9,<0.13"]
build-backend = "uv_build"
